import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {CSS2DRenderer,CSS2DObject} from 'three/addons/renderers/CSS2DRenderer.js';

const STORAGE_KEY='UTOP_NEEDLE_BALL_SNAPSHOT_V1';
const LAYOUT_PREFIX='UTOP_NEEDLE_BALL_LAYOUT_V2_';
const mount=document.getElementById('mount');
const stage=document.getElementById('stage');
const inspector=document.getElementById('inspector');
const inspectorContent=document.getElementById('inspectorContent');
const emptyState=document.getElementById('emptyState');
const presentationPointer=document.getElementById('presentationPointer');

const scene=new THREE.Scene();scene.background=new THREE.Color(0x06111d);
const camera=new THREE.PerspectiveCamera(48,1,.1,5000);camera.position.set(18,14,24);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;mount.appendChild(renderer.domElement);
const labelRenderer=new CSS2DRenderer();labelRenderer.domElement.style.position='absolute';labelRenderer.domElement.style.inset='0';labelRenderer.domElement.style.pointerEvents='none';mount.appendChild(labelRenderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=4;controls.maxDistance=180;
scene.add(new THREE.HemisphereLight(0xbfe8ff,0x182434,2.2));const keyLight=new THREE.DirectionalLight(0xffffff,2.4);keyLight.position.set(12,18,10);scene.add(keyLight);
const grid=new THREE.GridHelper(120,60,0x31516b,0x183047);grid.position.y=-7;scene.add(grid);
const root=new THREE.Group();scene.add(root);
let snapshot={devices:[],connections:[]};let deviceObjects=[],wireObjects=[],deviceRayTargets=[],rayTargets=[],groupLabelObjects=[];
let showLabels=true,showPorts=true,showWires=true,showGroupLabels=true,nodeScale=1,spacingScale=1.3,flowEnabled=true,pointerEnabled=false,focusedWire=null,selectedDevice=null;
let pendingWireRefresh=0;
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),clock=new THREE.Clock();
let dragged=null,dragPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0),dragOffset=new THREE.Vector3();

function toast(text){const el=document.createElement('div');el.className='nb-toast';el.textContent=text;stage.appendChild(el);setTimeout(()=>el.remove(),1600);}
function readSnapshot(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||{devices:[],connections:[]};}catch(_){return {devices:[],connections:[]};}}
function layoutKey(){const id=snapshot.projectId||snapshot.projectName||'default';return LAYOUT_PREFIX+String(id).replace(/[^a-zA-Z0-9_-]/g,'_');}
function portKind(name=''){const n=name.toUpperCase();if(n.includes('DI'))return'DI';if(n.includes('DO'))return'DO';if(n.includes('COM'))return'COM';if(n.includes('NO'))return'NO';if(n.includes('NC'))return'NC';if(/12V|24V|VCC|GND|POWER|電源/.test(n))return'POWER';if(/LAN|NET|RJ45|ETH|RS485|A\+|B-/.test(n))return'NETWORK';return'OTHER';}
const portColors={DI:0x4cc9f0,DO:0x72e06a,NO:0x47d16c,NC:0xffd166,COM:0xf08cff,POWER:0xff6464,NETWORK:0x6ea8ff,OTHER:0xc7d3df};
function makeLabel(text,className='nb-label'){const div=document.createElement('div');div.className=className;div.textContent=text;const obj=new CSS2DObject(div);obj.userData.labelElement=div;return obj;}
function collectPorts(device){const names=new Set();(snapshot.connections||[]).forEach(w=>{if(String(w.sourceId)===String(device.id)||w.sourceName===device.name)names.add(w.sourcePort||'DO');if(String(w.targetId)===String(device.id)||w.targetName===device.name)names.add(w.targetPort||'DI');});if(Array.isArray(device.ports))device.ports.forEach(p=>names.add(typeof p==='string'?p:(p?.name||p?.label||p?.id||'')));if(!names.size)['DI1','DO1','COM'].forEach(n=>names.add(n));return[...names].filter(Boolean).slice(0,48);}
function savedLayout(){try{return JSON.parse(localStorage.getItem(layoutKey())||'{}');}catch(_){return{};}}
function saveLayout(silent=false){const data={};deviceObjects.forEach(g=>{const d=g.userData.device;data[String(d.id||d.name)]={x:g.position.x,y:g.position.y,z:g.position.z};});localStorage.setItem(layoutKey(),JSON.stringify(data));if(!silent)toast('針球排列已保存');}
function applySavedPosition(group,device){const p=savedLayout()[String(device.id||device.name)];if(p&&[p.x,p.y,p.z].every(Number.isFinite)){group.position.set(p.x,p.y,p.z);return true;}return false;}
function buildDevice(device,index,total){
 const group=new THREE.Group();group.userData={kind:'device',device};
 const degree=(snapshot.connections||[]).filter(w=>w.sourceName===device.name||w.targetName===device.name||String(w.sourceId)===String(device.id)||String(w.targetId)===String(device.id)).length;
 const radius=1.35+Math.min(degree,12)*.055;const mat=new THREE.MeshStandardMaterial({color:degree?0x168aad:0x405a70,roughness:.34,metalness:.28,emissive:degree?0x052a38:0x07111b,transparent:true,opacity:1});
 const sphere=new THREE.Mesh(new THREE.SphereGeometry(radius,36,24),mat);sphere.userData={kind:'device',device,root:group};group.add(sphere);deviceRayTargets.push(sphere);
 const label=makeLabel(device.name);label.position.set(0,radius+1.45,0);label.userData.isDeviceLabel=true;group.add(label);
 const ports=collectPorts(device);group.userData.portMap=new Map();
 ports.forEach((name,i)=>{const phi=Math.acos(1-2*(i+.5)/ports.length),theta=Math.PI*(1+Math.sqrt(5))*i;const dir=new THREE.Vector3(Math.sin(phi)*Math.cos(theta),Math.cos(phi),Math.sin(phi)*Math.sin(theta));const start=dir.clone().multiplyScalar(radius*.96),end=dir.clone().multiplyScalar(radius+1.85);const kind=portKind(name);const stem=new THREE.Line(new THREE.BufferGeometry().setFromPoints([start,end]),new THREE.LineBasicMaterial({color:portColors[kind],transparent:true,opacity:.9}));stem.userData={isPortStem:true,portKind:kind};group.add(stem);const tip=new THREE.Mesh(new THREE.SphereGeometry(.22,18,14),new THREE.MeshStandardMaterial({color:portColors[kind],emissive:portColors[kind],emissiveIntensity:.18,transparent:true,opacity:1}));tip.position.copy(end);tip.userData={kind:'port',device,port:name,portKind:kind,root:group};group.add(tip);deviceRayTargets.push(tip);const pl=makeLabel(name,'nb-port-label');pl.position.copy(end.clone().multiplyScalar(1.08));pl.userData.isPortLabel=true;pl.userData.portKind=kind;group.add(pl);group.userData.portMap.set(name,tip);});
 const angle=index/Math.max(total,1)*Math.PI*2,ring=Math.ceil((index+1)/8),r=(9+ring*5.2)*spacingScale;group.position.set(Math.cos(angle)*r,(index%3-1)*2.5,Math.sin(angle)*r);applySavedPosition(group,device);root.add(group);deviceObjects.push(group);return group;
}
function findDevice(wire,side){const id=String(wire[`${side}Id`]||''),name=wire[`${side}Name`];return deviceObjects.find(g=>String(g.userData.device.id)===id)||deviceObjects.find(g=>g.userData.device.name===name);}
function endpoint(group,port){return group?.userData.portMap?.get(port)?.getWorldPosition(new THREE.Vector3())||group?.getWorldPosition(new THREE.Vector3())||new THREE.Vector3();}
function disposeWire(o){o.traverse(c=>{if(c.element){try{c.element.remove()}catch(_){}}c.geometry?.dispose?.();if(Array.isArray(c.material))c.material.forEach(m=>m.dispose?.());else c.material?.dispose?.();});root.remove(o);}
function clearGroupLabels(){groupLabelObjects.forEach(o=>{root.remove(o);if(o.element)o.element.remove();});groupLabelObjects=[];}
function addGroupLabel(text,position){const label=makeLabel(text,'nb-group-label');label.position.copy(position);label.userData.isGroupLabel=true;label.visible=showGroupLabels;root.add(label);groupLabelObjects.push(label);}
function buildWires(){wireObjects.forEach(disposeWire);wireObjects=[];rayTargets=[...deviceRayTargets];(snapshot.connections||[]).forEach((wire,index)=>{const a=findDevice(wire,'source'),b=findDevice(wire,'target');if(!a||!b)return;const p1=endpoint(a,wire.sourcePort),p2=endpoint(b,wire.targetPort),mid=p1.clone().lerp(p2,.5);mid.y+=Math.max(1.2,p1.distanceTo(p2)*.12)+(index%4)*.35;const curve=new THREE.QuadraticBezierCurve3(p1,mid,p2);const mat=new THREE.MeshBasicMaterial({color:wire.active?0x7cff8a:0x79cfff,transparent:true,opacity:.96,depthTest:false,depthWrite:false});const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,48,.105,10,false),mat);tube.renderOrder=8;tube.userData={kind:'wire',wire,source:a,target:b,curve,baseOpacity:.84};root.add(tube);wireObjects.push(tube);rayTargets.push(tube);const label=makeLabel(`${wire.sourceName||a.userData.device.name}.${wire.sourcePort} → ${wire.targetName||b.userData.device.name}.${wire.targetPort}`,'nb-port-label');label.position.copy(mid);label.userData.isWireLabel=true;tube.add(label);const particle=new THREE.Mesh(new THREE.SphereGeometry(.17,14,10),new THREE.MeshBasicMaterial({color:wire.active?0x9affaa:0x73d8ff,transparent:true,opacity:.95}));particle.userData.isFlowParticle=true;particle.visible=flowEnabled&&showWires;tube.add(particle);tube.userData.particle=particle;const arrow=new THREE.Mesh(new THREE.ConeGeometry(.22,.68,14),new THREE.MeshBasicMaterial({color:wire.active?0xb4ffbd:0xa6e8ff,transparent:true,opacity:.96}));arrow.userData.isFlowArrow=true;arrow.visible=flowEnabled&&showWires;tube.add(arrow);tube.userData.arrow=arrow;});applyVisibility();if(focusedWire)focusWire(focusedWire,true);}
function rebuild(){while(root.children.length)root.remove(root.children[0]);deviceObjects=[];wireObjects=[];deviceRayTargets=[];rayTargets=[];groupLabelObjects=[];focusedWire=null;selectedDevice=null;document.getElementById('projectName').textContent=snapshot.projectName||'端子與接線立體檢視';document.getElementById('deviceCount').textContent=`${snapshot.devices?.length||0}個模組`;document.getElementById('wireCount').textContent=`${snapshot.connections?.length||0}條接線`;emptyState.hidden=Boolean(snapshot.devices?.length);(snapshot.devices||[]).forEach((d,i)=>buildDevice(d,i,snapshot.devices.length));buildWires();applyVisibility();resetView();}
function applyVisibility(){const enabled=new Set([...document.querySelectorAll('[data-filter]:checked')].map(el=>el.dataset.filter));deviceObjects.forEach(g=>g.traverse(o=>{if(o.userData?.isDeviceLabel)o.visible=showLabels;if(o.userData?.isPortLabel)o.visible=showPorts&&enabled.has(o.userData.portKind||'OTHER')&&(selectedDevice===g||deviceObjects.length<=5);if(o.userData?.kind==='port'||o.userData?.isPortStem)o.visible=showPorts&&enabled.has(o.userData.portKind||'OTHER');}));wireObjects.forEach(w=>{w.visible=showWires;w.children.forEach(c=>{if(c.userData?.isWireLabel)c.visible=showLabels&&showWires&&(focusedWire===w||wireObjects.length<=8);if(c.userData?.isFlowParticle||c.userData?.isFlowArrow)c.visible=flowEnabled&&showWires;});});}
function autoLayout(){const count=deviceObjects.length;if(!count)return;const cols=Math.ceil(Math.sqrt(count));deviceObjects.forEach((g,i)=>{const row=Math.floor(i/cols),col=i%cols,x=(col-(cols-1)/2)*6*spacingScale,z=(row-(Math.ceil(count/cols)-1)/2)*6*spacingScale;g.position.set(x,((i%3)-1)*1.7,z);});clearFocus();buildWires();saveLayout(true);toast('已完成自動排列');}
function groupKey(d){return String(d.category||d.group||d.system||d.type||'其他');}
function groupLayout(){clearGroupLabels();const groups=new Map();deviceObjects.forEach(g=>{const k=groupKey(g.userData.device);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(g);});const entries=[...groups.entries()],groupRadius=Math.max(7,entries.length*2.3)*spacingScale;entries.forEach(([name,list],gi)=>{const ga=gi/Math.max(entries.length,1)*Math.PI*2,center=new THREE.Vector3(Math.cos(ga)*groupRadius,0,Math.sin(ga)*groupRadius);list.forEach((g,i)=>{const a=i/Math.max(list.length,1)*Math.PI*2,r=Math.max(2.7,list.length*.55)*spacingScale;g.position.set(center.x+Math.cos(a)*r,(i%3-1)*1.4,center.z+Math.sin(a)*r);});addGroupLabel(`${name}（${list.length}）`,center.clone().add(new THREE.Vector3(0,4.4,0)));});clearFocus();buildWires();saveLayout(true);toast(`已依${entries.length}個設備群組排列`);}
function resetView(){camera.position.set(18,14,24);controls.target.set(0,0,0);controls.update();}
function setObjectOpacity(group,opacity){group.traverse(o=>{if(o.material&&'opacity'in o.material){o.material.transparent=true;o.material.opacity=opacity;}});}
function clearFocus(){focusedWire=null;selectedDevice=null;wireObjects.forEach(w=>{w.material.opacity=w.userData.baseOpacity;w.children.forEach(c=>{if(c.element)c.element.style.opacity='1';});});deviceObjects.forEach(g=>setObjectOpacity(g,1));document.getElementById('focusClearBtn').classList.remove('is-active');applyVisibility();}
function focusWire(target,silent=false){const obj=target?.userData?.kind==='wire'?target:wireObjects.find(w=>w.userData.wire===target||w.userData.wire?.id===target?.id);if(!obj)return;focusedWire=obj;const keep=new Set([obj.userData.source,obj.userData.target]);wireObjects.forEach(w=>{w.material.opacity=w===obj?1:.07;w.children.forEach(c=>{if(c.element)c.element.style.opacity=w===obj?'1':'0.08';});});deviceObjects.forEach(g=>setObjectOpacity(g,keep.has(g)?1:.16));document.getElementById('focusClearBtn').classList.add('is-active');applyVisibility();if(!silent)toast('已聚焦單一接線，按「顯示全部」恢復');}
function focusDeviceCircuit(startGroup){if(!startGroup)return;selectedDevice=startGroup;const keepDevices=new Set([startGroup]),keepWires=new Set();const queue=[startGroup];while(queue.length){const current=queue.shift();wireObjects.forEach(w=>{if(w.userData.source!==current&&w.userData.target!==current)return;if(keepWires.has(w))return;keepWires.add(w);const other=w.userData.source===current?w.userData.target:w.userData.source;if(other&&!keepDevices.has(other)){keepDevices.add(other);queue.push(other);}});}wireObjects.forEach(w=>{const keep=keepWires.has(w);w.material.opacity=keep?1:.035;w.children.forEach(c=>{if(c.element)c.element.style.opacity=keep?'1':'0.04';});});deviceObjects.forEach(g=>setObjectOpacity(g,keepDevices.has(g)?1:.1));document.getElementById('focusClearBtn').classList.add('is-active');toast(`已顯示「${startGroup.userData.device.name}」完整迴路：${keepDevices.size}個模組、${keepWires.size}條線`);}

function showInfo(data){inspector.classList.add('is-open');if(data.kind==='device'){const d=data.device,ports=collectPorts(d);selectedDevice=data.root||deviceObjects.find(g=>g.userData.device===d)||null;applyVisibility();inspectorContent.innerHTML=`<div class="nb-card"><strong>${d.name}</strong><span>類型：${d.type||'設備'}</span><span>群組：${groupKey(d)}</span><span>編號：${d.modelCode||d.id}</span><small>端子：${ports.join('、')}</small></div>`;}else if(data.kind==='port'){inspectorContent.innerHTML=`<div class="nb-card"><strong>${data.port}</strong><span>設備：${data.device.name}</span><span>分類：${data.portKind}</span></div>`;}else if(data.kind==='wire'){const w=data.wire;inspectorContent.innerHTML=`<div class="nb-card nb-route"><div><strong>${w.sourceName}</strong><b>${w.sourcePort}</b></div><span>→</span><div><strong>${w.targetName}</strong><b>${w.targetPort}</b></div></div><div class="nb-card"><span>類型：${w.type||'signal'}</span><span>狀態：${w.active?'有訊號':'待命'}</span><small>已聚焦此線路，其他設備與線路暫時淡化。</small></div>`;}}
function scheduleWireRefresh(){if(pendingWireRefresh)return;pendingWireRefresh=requestAnimationFrame(()=>{pendingWireRefresh=0;buildWires();});}
function hitFromEvent(event){const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(rayTargets,false)[0]||null;}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0||pointerEnabled)return;const hit=hitFromEvent(e);if(!hit)return;showInfo(hit.object.userData);if(hit.object.userData.kind==='wire'){focusWire(hit.object);return;}if(hit.object.userData.kind==='device'){dragged=hit.object.userData.root;controls.enabled=false;dragPlane.set(new THREE.Vector3(0,1,0),-dragged.position.y);const p=new THREE.Vector3();raycaster.ray.intersectPlane(dragPlane,p);dragOffset.copy(dragged.position).sub(p);renderer.domElement.setPointerCapture(e.pointerId);}});
renderer.domElement.addEventListener('pointermove',e=>{if(pointerEnabled){const r=stage.getBoundingClientRect();presentationPointer.style.left=`${e.clientX-r.left}px`;presentationPointer.style.top=`${e.clientY-r.top}px`;return;}if(!dragged)return;hitFromEvent(e);const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(dragPlane,p)){dragged.position.copy(p.add(dragOffset));scheduleWireRefresh();}});
function endDrag(e){if(!dragged)return;dragged=null;controls.enabled=true;buildWires();saveLayout(true);try{renderer.domElement.releasePointerCapture(e.pointerId)}catch(_){}}
renderer.domElement.addEventListener('pointerup',endDrag);renderer.domElement.addEventListener('pointercancel',endDrag);renderer.domElement.addEventListener('pointerleave',()=>{if(pointerEnabled)presentationPointer.hidden=true;});renderer.domElement.addEventListener('pointerenter',()=>{if(pointerEnabled)presentationPointer.hidden=false;});
function togglePointer(force){pointerEnabled=typeof force==='boolean'?force:!pointerEnabled;presentationPointer.hidden=!pointerEnabled;renderer.domElement.style.cursor=pointerEnabled?'none':'';controls.enabled=!pointerEnabled;const btn=document.getElementById('pointerBtn');btn.classList.toggle('is-warning',pointerEnabled);btn.textContent=pointerEnabled?'⚪ 關閉指揮棒':'🔴 指揮棒';}
function resize(){const r=stage.getBoundingClientRect();camera.aspect=r.width/Math.max(r.height,1);camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false);labelRenderer.setSize(r.width,r.height);}new ResizeObserver(resize).observe(stage);resize();
function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();controls.update();if(flowEnabled&&showWires)wireObjects.forEach((w,i)=>{const p=w.userData.particle,a=w.userData.arrow;if(!p&&!a)return;const speed=w.userData.wire?.active?.34:.16;const u=(t*speed+i*.17)%1,curve=w.userData.curve,point=curve.getPointAt(u),next=curve.getPointAt(Math.min(.999,u+.012)),tangent=next.clone().sub(point).normalize();if(p)p.position.copy(point);if(a){a.position.copy(point);a.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),tangent);}});renderer.render(scene,camera);labelRenderer.render(scene,camera);}animate();

document.getElementById('autoLayoutBtn').onclick=autoLayout;document.getElementById('groupLayoutBtn').onclick=groupLayout;document.getElementById('resetViewBtn').onclick=resetView;
document.getElementById('labelsBtn').onclick=e=>{showLabels=!showLabels;e.currentTarget.classList.toggle('is-active',showLabels);e.currentTarget.textContent=`🏷 名稱：${showLabels?'開':'關'}`;applyVisibility();};
document.getElementById('portsBtn').onclick=e=>{showPorts=!showPorts;e.currentTarget.classList.toggle('is-active',showPorts);e.currentTarget.textContent=`✳ 端子：${showPorts?'開':'關'}`;applyVisibility();};
document.getElementById('wiresBtn').onclick=e=>{showWires=!showWires;e.currentTarget.classList.toggle('is-active',showWires);e.currentTarget.textContent=`〰 接線：${showWires?'開':'關'}`;applyVisibility();};
document.getElementById('flowBtn').onclick=e=>{flowEnabled=!flowEnabled;e.currentTarget.classList.toggle('is-active',flowEnabled);e.currentTarget.textContent=`➤ 訊號流動：${flowEnabled?'開':'關'}`;applyVisibility();};
document.getElementById('focusClearBtn').onclick=clearFocus;document.getElementById('circuitFocusBtn').onclick=()=>{if(!selectedDevice){toast('請先點選一個模組球');return;}focusDeviceCircuit(selectedDevice);};document.getElementById('groupLabelsBtn').onclick=e=>{showGroupLabels=!showGroupLabels;e.currentTarget.classList.toggle('is-active',showGroupLabels);e.currentTarget.textContent=`🧭 群組名稱：${showGroupLabels?'開':'關'}`;groupLabelObjects.forEach(o=>o.visible=showGroupLabels);};document.getElementById('saveLayoutBtn').onclick=()=>saveLayout(false);document.getElementById('pointerBtn').onclick=()=>togglePointer();
document.getElementById('nodeSize').oninput=e=>{nodeScale=Number(e.target.value)/100;deviceObjects.forEach(g=>g.scale.setScalar(nodeScale));buildWires();};document.getElementById('spacing').oninput=e=>{spacingScale=Number(e.target.value)/100;autoLayout();};
document.getElementById('fullscreenBtn').onclick=async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen?.();};
document.getElementById('refreshBtn').onclick=()=>{snapshot=readSnapshot();rebuild();};
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='p'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||''))togglePointer();if(e.key==='Escape'&&pointerEnabled)togglePointer(false);});
window.addEventListener('message',event=>{if(event.origin!==location.origin||event.data?.type!=='UTOP_NEEDLE_BALL_SNAPSHOT')return;snapshot=event.data.payload||readSnapshot();localStorage.setItem(STORAGE_KEY,JSON.stringify(snapshot));rebuild();});
document.querySelectorAll('[data-filter]').forEach(input=>input.addEventListener('change',applyVisibility));snapshot=readSnapshot();rebuild();
