[build]
  publish = "."

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/runtime/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/runtime/*/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
